language: node_js

node_js:
  - stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - "node_modules"

install: yarn

script: yarn build

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run semantic-release
