[build]
  publish = "public"
  command = "yarn build"

[build.environment]
  YARN_VERSION = "1.22.4"
  NODE_VERSION = "12.18.2"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_OPTIONS = "--max_old_space_size=4096"
  GATSBY_SITE_URL = "https://gatsby-reapt.netlify.com"
